DATASET:
  NAME: "LGG"
  NUM_CLASSES: 2
  PATIENT_SPARSITY_RATES: 0.85

ACO:
  MAX_ITERS: 2
  NUM_AGENTS: 1
  FIX_FEAT_SIZE: 2
  FINAL_FEAT_SIZES: [300]

SOLVER:
  MAX_EPOCHS_PRETRAIN: 2
  MAX_EPOCHS: 2

GAT:
  NUM_HEADS: 2
  DROPOUT_RATE: 0.3
  LR_PRETRAIN: 1e-3
  LR: 1e-3

VCDN:
  LR: 5e-2

RESULT:
  SAVE_RICH_DATA: True
  SAVE_MODEL: True
