DATASET:
  NAME: "LGG"
  NUM_CLASSES: 2
  CLASS_NAMES: [ "Grade II", "Grade III" ]
  PATIENT_SPARSITY_RATES: 0.85

GAT:
  NUM_HEADS: 2
  DROPOUT_RATE: 0.3
  LR_PRETRAIN: 1e-3
  LR: 1e-3

VCDN:
  LR: 5e-2
