DATASET:
  NAME: "RCC"
  NUM_CLASSES: 3
  CLASS_NAMES: [ "KICH", "KIRC", "KIRP" ]
  PATIENT_SPARSITY_RATES: 0.80

GAT:
  NUM_HEADS: 2
  DROPOUT_RATE: 0.0
  LR_PRETRAIN: 1e-3
  LR: 1e-3

VCDN:
  LR: 5e-2
